name: My first workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        
      - name: Welcome message
        run: echo "Whatup Doe?"
      
      - name: List files
        run: ls 

      - name: Read file
        run: cat README.md
