name: My first workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: List and read files
        run: |
          echo "Whatup Doe?"
          ls -ltra
          cat README.md

      - name: Generate ASCII Artwork
        run: cosway -f dragon "I hope you like it HOT" >> dragon.txt 

      # - name: List files
      #   run: ls 

      # - name: Read file
      #   run: cat README.md
