name: Generate ASCII Artwork

on: push

jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: List repo files
        run: ls -ltra

      - name: Executing Shell Script
        run: |
          chmod +x ascii-scripts.sh
          ./ascii-scripts.sh

      # - name: Test File Exists
      #   run: |
      #     if [ -f "dragon.txt" ]; then
      #       echo "File exists!"
      #     else
      #       echo "File does not exist!"
      #       exit 1
      #     fi



